### ISSUE TITLE
Use of Extra Libraries

### ISSUE THREAD

**Issue by amjadraza** [langchain-ai/streamlit-agent#11]
Do we really need it, I don't see explicit use of these rather adding extra space and time to create an environment. 

sentence-transformers = "^2.2.2"
torch = ">=2.0.0, !=2.0.1"

**Comment by Muhtasham** [comment]
They are needed for document question answering demo and probably
assumption of
repo maintainers is for all demos to run simply, if you want you can
stratify environments on per demo basis and open PR

**Comment by amjadraza** [comment]
When I was building a Docker Container, the size of Docker went more than 5GB, and the same for building a project Virtual Environment.

**Comment by sfc-gh-jcarroll** [comment]
Yes, it gets quite large. Wanted to make it easy to install and run any of the examples. Ideas on how to reduce the footprint while keeping it simple to use and support all the examples are welcome!

**Comment by Muhtasham** [comment]
I like this approach quite simple

https://github.com/nlp-with-transformers/notebooks/blob/main/install.py

**Comment by amjadraza** [comment]
@sfc-gh-jcarroll @Muhtasham Closing this issue as it is on purpose with the objective to support more apps in future.
