### ISSUE TITLE
Is there a way to prompt the user with the "human" tool?

### ISSUE THREAD

**Issue by Jgmedina95** [langchain-ai/streamlit-agent#21]
I love this repo, and is very useful. Although im wondering if there's an implementation to prompt the user for the "human" tool. Cause as of now, everything happens in the background, and when the human is "prompted" nothing happens.

**Comment by sfc-gh-jcarroll** [comment]
Hey, not sure I understand the question. Want to share a little more details - which app are you running? What's the repro steps and what specific behavior did you see? It doesn't sound familiar from my experience playing with all the apps. Thanks!

**Comment by Jgmedina95** [comment]
hi! In this particular case, i had an agent that used multiple tools. When trying to use it with streamlit for a nice UI, I was running into the bug that whenever the agent wanted to use the "human" tool from langchain. There was no input pop up for the user, so it seemed that the agent was just thinking continuously. Maybe that was a better description? 
sadly I cant share the code as it was part of an internship I was doing.

**Comment by sfc-gh-jcarroll** [comment]
Ah I see - might be a good question for the langchain discord if it's about the agent behavior. Going to close this since it seems like more of a general request vs a particular issue with this repo. Thank you!

**Comment by amjadraza** [comment]
@sfc-gh-jcarroll I am having this issue as well. If you find anything, let me know. 

For user input when running agent, I need this tool to have interaction with agent while running the job

**Comment by sfc-gh-jcarroll** [comment]
Can you post a sample app to show the issue?
