### ISSUE TITLE
Error message in console when running  chat_with_documents.py

### ISSUE THREAD

**Issue by rubensmau** [langchain-ai/streamlit-agent#24]
When running chat_with_documents.py , I get the following error message

Error in PrintRetrievalHandler.on_retriever_start callback: PrintRetrievalHandler.on_retriever_start() takes 2 positional arguments but 3 were given

Apparently, it still works fine, and PrintRetrievalHandler.on_retriever_start() can be commented out

**Comment by sfc-gh-jcarroll** [comment]
Fixed by #29, thanks for reporting and thanks @bruno-uy for the fix!!
