### ISSUE TITLE
Hosted version build is failing

### ISSUE THREAD

**Issue by davidzshi** [langchain-ai/streamlit-agent#26]
See the error below. 

<img width="774" alt="Screen Shot 2023-08-21 at 5 40 00 PM" src="https://github.com/langchain-ai/streamlit-agent/assets/19938602/9dc7f91f-a89d-4bc8-93b6-11e2138b1c94">

**Comment by sfc-gh-jcarroll** [comment]
Fixed by https://github.com/langchain-ai/streamlit-agent/pull/27, thank you!
