### ISSUE TITLE
Is there a way to prevent thoughts from disappearing?

### ISSUE THREAD

**Issue by sradc** [langchain-ai/streamlit-agent#36]
I.e. the intermediate thoughts appear in the most recent answer from the agent. However, when more messages are added, the intermediate thoughts disappear from the older answers (leaving just the final answer). I would like to be able leave the intermediate thoughts in place, to allow going back and inspecting them.

**Comment by sfc-gh-jcarroll** [comment]
Hi, we don't have a simple built in way to do it, but you can retrieve the `intermediate_steps` object from the agent response and use that to re-draw the status in future streamlit reruns so it's persisted.

See a simple implementation [here, particularly the highlighted portion](https://github.com/langchain-ai/streamlit-agent/blob/0e14931196fc72edf66d6a19968dc738d4df3b1e/streamlit_agent/search_and_chat.py#L27-L32).
