### ISSUE TITLE
LangChain: Chat with search is not working

### ISSUE THREAD

**Issue by truecaptions** [langchain-ai/streamlit-agent#44]
![image](https://github.com/langchain-ai/streamlit-agent/assets/151957641/976c7d49-1451-4d3e-9b5b-58e9cbbee7c5)

I have several times, but its not working!

**Comment by tjaensch** [comment]
Same thing... this app stopped working a while ago. Some problem with duckduckgo search.

**Comment by sfc-gh-jcarroll** [comment]
Thanks for reporting, I'll take a look when I have a bit of time :)

**Comment by hcy1251** [comment]
I think MRKL is not working as well, it might be the same issue as Chat with search.

**Comment by sfc-gh-jcarroll** [comment]
I just updated everything to langchain 0.1 and cleaned up the various imports and calls to conform to the latest APIs. Everything is running now for me locally and restarted the hosted versions. Didn't fix the deprecation warnings on everything but addressed a lot of them. LMK if you still see issues with a clean install.
