### ISSUE TITLE
Clang: error - Poetry install on Apple-M1

### ISSUE THREAD

**Issue by utkucanaytac** [langchain-ai/streamlit-agent#7]
When installing dependencies from the lock file with poetry,  M1 users will `get clang: error: the clang compiler does not support '-march=native'`

I found a workaround by setting an environment variable (Ref:https://stackoverflow.com/a/75870031/12906920)
`export HNSWLIB_NO_NATIVE=1  `
then
`poetry install`

Just wanted to inform this issue. 

Thanks.

**Comment by bruno-uy** [comment]
I didn't have this error, and I'm using M1.

Things I ran in the terminal:
```
conda create -n streamlit-agent python=3.11
conda activate streamlit-agent
# Make sure you don't have `poetry` or `cleo` installed. Remove them with `pip uninstall` if you do.
curl -sSL https://install.python-poetry.org | python3 -
export PATH="/Users/<your_user>/.local/bin:$PATH"
poetry install
poetry shell
pre-commit install
```

Hope it helps

**Comment by sfc-gh-jcarroll** [comment]
Thank you!!
